### ISSUE TITLE
Level cost text on the PMPro membership account page remains unchanged when a discount code is used

### ISSUE THREAD

**Issue by MaryOJob** [strangerstudios/paystack-gateway-paid-memberships-pro#2]
**Describe the bug**
The level cost text on the PMPro membership account page remains unchanged for a recurring membership when a discount code with a different amount is used. The subscription is not also created for this checkout on the Paystack merchant account dashboard.

**To Reproduce**
1. Set up a recurring payment discount code for any of your levels
2. Checkout with the discount code
3. Navigate to the PMPro account page, the level cost text reflects that of the membership level, not the appropriate cost text for the discount code that was used

![Screenshot 2024-02-06 at 19 53 08](https://github.com/strangerstudios/paystack-gateway-paid-memberships-pro/assets/25005583/bb222d53-58ac-43e3-9105-2b36aa4ad851)

<img width="877" alt="Screenshot 2024-02-06 at 19 53 39" src="https://github.com/strangerstudios/paystack-gateway-paid-memberships-pro/assets/25005583/98cc8ce0-856e-403f-a825-472789d1815c">

<img width="876" alt="Screenshot 2024-02-06 at 19 54 04" src="https://github.com/strangerstudios/paystack-gateway-paid-memberships-pro/assets/25005583/82dda541-185e-4d68-b68a-af1f798403a9">

<img width="882" alt="Screenshot 2024-02-06 at 19 54 27" src="https://github.com/strangerstudios/paystack-gateway-paid-memberships-pro/assets/25005583/fa17fab2-e437-4675-9a15-c1e20c66845d">

**Expected behavior**
The level cost text should read the amount paid and the amount to be paid on a recurring basis per the discount code applied

**Isolating the problem (mark completed items with an [x]):**
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.
**WordPress Environment**
<details>
```
Paid Memberships Pro 2.12.8
WordPress 6.4.3
PHP 7.4.33
Memberlite 5.1.0
PMPro Paystack 1.7.1
```
</details>

**Comment by MaryOJob** [comment]
Note that the same behavior occurs when the discount code is set to a one-time initial payment with an expiry date.

And the discount code count remains unchanged whether it is a discount code set to unlimited use or a number of uses.

<img width="835" alt="Screenshot 2024-02-06 at 20 13 44" src="https://github.com/strangerstudios/paystack-gateway-paid-memberships-pro/assets/25005583/4473c931-07fb-4ee5-b8a6-634f45eb1cea">

![Screenshot 2024-02-06 at 20 15 49](https://github.com/strangerstudios/paystack-gateway-paid-memberships-pro/assets/25005583/be5d877c-5eed-4901-966d-bd414ab45d9b)

**Comment by andrewlimaza** [comment]
Some further feedback. 

This does charge the correct amount it just doesn't track that the discount code was used which causes issues of displaying the incorrect amount.

To be fixed: Make sure we track the discount code was used.

**Comment by MaryOJob** [comment]
Yes, that is accurate, @andrewlimaza, the correct amount is charged, but the discount code use is not tracked, hence the wrong level cost text.
