### ISSUE TITLE
Memberships cancelled on PmPro still show up as Active on Paystack

### ISSUE THREAD

**Issue by OgheneTega** [strangerstudios/paystack-gateway-paid-memberships-pro#7]
Hello team,

I'm reaching out on behalf of the developer relations team at Paystack.

We've received a report that subscriptions paid for via Paystack remain active after being cancelled on the admin side in PmPro. This means users continue to be charged the plan price without receiving the associated benefits.

Expected behavior: When memberships are cancelled on the PmPro dashboard, they should also be cancelled in Paystack.

We've replicated this issue and confirmed that webhooks are properly set.

I will be on standby to assist with anything you may need to further this investigation.

**Comment by andrewlimaza** [comment]
@OgheneTega sorry for missing this, we don't actively monitor GitHub for support requests. 

However, I tried testing this and wasn't able to replicate it. I tried cancelling as an admin, as well as a member and both times the subscription changes to status "Non-Renewing".

Please let me know what steps to I need to take to replicate this and debug it further.

I am available on the Paystack slack and happy to chat about these issues more.

**Comment by OgheneTega** [comment]
Hello @andrewlimaza,

I'd appreciate the opportunity to chat on the Paystack Slack. How can I reach you?

**Comment by andrewlimaza** [comment]
Closing as it seems to be resolved. Thanks!
