### ISSUE TITLE
Membership price is updated but payment not reflecting

### ISSUE THREAD

**Issue by OgheneTega** [strangerstudios/paystack-gateway-paid-memberships-pro#8]
Hello team,

We've encountered an issue where the membership price has been updated (e.g., reviewed upwards), and customers are being charged the new price. However, these payments are not reflecting in the customer's portal on PmPro.

We have tested and confirmed the existence of this issue.

I'm glad to assist with whatever you may need to ease your debugging process.

**Comment by andrewlimaza** [comment]
Hi @OgheneTega 

Can you please provide me with steps to replicate this? I'd like to look into this further.

**Comment by andrewlimaza** [comment]
@OgheneTega I was able to replicate this issue and working through this to be included in the next release. Currently I do not have any estimate when this will be available but it's on our radar.

**Comment by andrewlimaza** [comment]
This has been resolved with V1.7.5 and can confirm that it pulls the amount from the webhook received. Please let us know if you experience any further issues.
